# Generated by Django 4.0.3 on 2022-04-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='custo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
