# Generated by Django 4.0.3 on 2022-04-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_produto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
