# Generated by Django 4.0.3 on 2022-04-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_produto_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
