# Generated by Django 4.0.3 on 2022-04-14 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_administrador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
